### ISSUE TITLE
debug_traceTransaction fails on forked chain

### ISSUE THREAD

**Issue by kimiylilammi** [trufflesuite/ganache-core#404]
Forking a chain and calling "debug_traceTransaction" throws exception "Error: Number can only safely store up to 53 bits" with a simple transaction.

## Expected Behavior
debug_traceTransaction should return trace

## Current Behavior
after calling debug_traceTransaction genache-cli throws error "Error: Number can only safely store up to 53 bits"

## Steps to Reproduce (for bugs)
1. Run parity/geth full node with tracing
2. Fork: ganache-cli --fork http://localhost:8545@100 --port 9999 --debug --db chain/
3. Send test transaction and try to trace it:
from web3 import Web3, HTTPProvider, TestRPCProvider
web3 = Web3(HTTPProvider("http://127.0.0.1:9999")
message = {
  "from": public_address,
  "to": address,
  "value": 1
}
result = web3.eth.sendTransaction(message)
trace = web3.manager.request_blocking("debug_traceTransaction", [result])

## Your Environment

* Version used:  Ganache CLI v6.0.3 (ganache-core: 2.0.2)
* Server type and version: Geth 1.7.3, Parity/1.8.3/1.20.0/wi, web3py
* Operating System and version: Windows 10

**Comment by davidmurdoch** [comment]
This should now be fixed (again) in our latest beta https://github.com/trufflesuite/ganache-core/releases/tag/v2.5.5-beta.0 Let me know if you have any more issues or if the fix doesn't work for you!

**Comment by gnidan** [comment]
Hey @davidmurdoch I just tried this out and I can't get this working on ganache-cli@2.5.5.

I'm running `ganache-cli --port 4545 --host 0.0.0.0 --fork http://my.ethchain.dnp.dappnode.eth:8545` and I've got the corresponding network setup in my Truffle config. Inside my Truffle console I'm running the function exported by this module:
```javascript
const { promisify } = require("util");

module.exports = async (web3, txHash) => {
  return await promisify(web3.currentProvider.send)({
    jsonrpc: "2.0",
    method: "debug_traceTransaction",
    params: [txHash, {}],
    id: new Date().getTime()
  });
}
```

This causes ganache-cli to crash with this exception:
```
Error: Given input "�Ϭ�(P�...#ǯ%K�y " is not a number.
    at Object.p (/Users/gnidan/.nvm/versions/node/v8.15.0/lib/node_modules/ganache-cli/build/ganache-core.node.cli.js:47:264131)
    at f.c (/Users/gnidan/.nvm/versions/node/v8.15.0/lib/node_modules/ganache-cli/build/ganache-core.node.cli.js:69:20807)
    at /Users/gnidan/.nvm/versions/node/v8.15.0/lib/node_modules/ganache-cli/build/ganache-core.node.cli.js:2:93803
    at Array.map (<anonymous>)
    at f.formatInput (/Users/gnidan/.nvm/versions/node/v8.15.0/lib/node_modules/ganache-cli/build/ganache-core.node.cli.js:2:93774)
    at f.toPayload (/Users/gnidan/.nvm/versions/node/v8.15.0/lib/node_modules/ganache-cli/build/ganache-core.node.cli.js:2:94105)
    at _.r [as getBlock] (/Users/gnidan/.nvm/versions/node/v8.15.0/lib/node_modules/ganache-cli/build/ganache-core.node.cli.js:2:97947)
    at h.getFallbackBlock (/Users/gnidan/.nvm/versions/node/v8.15.0/lib/node_modules/ganache-cli/build/ganache-core.node.cli.js:69:9343)
    at call (/Users/gnidan/.nvm/versions/node/v8.15.0/lib/node_modules/ganache-cli/build/ganache-core.node.cli.js:69:10333)
    at /Users/gnidan/.nvm/versions/node/v8.15.0/lib/node_modules/ganache-cli/build/ganache-core.node.cli.js:69:9256
    at /Users/gnidan/.nvm/versions/node/v8.15.0/lib/node_modules/ganache-cli/build/ganache-core.node.cli.js:61:1870989
    at /Users/gnidan/.nvm/versions/node/v8.15.0/lib/node_modules/ganache-cli/build/ganache-core.node.cli.js:61:1865292
    at /Users/gnidan/.nvm/versions/node/v8.15.0/lib/node_modules/ganache-cli/build/ganache-core.node.cli.js:61:1862655
    at /Users/gnidan/.nvm/versions/node/v8.15.0/lib/node_modules/ganache-cli/build/ganache-core.node.cli.js:61:1883530
    at /Users/gnidan/.nvm/versions/node/v8.15.0/lib/node_modules/ganache-cli/build/ganache-core.node.cli.js:61:1890907
    at ReadFileContext.callback (/Users/gnidan/.nvm/versions/node/v8.15.0/lib/node_modules/ganache-cli/build/ganache-core.node.cli.js:61:1889369)
    at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:420:13)
```

This is forking off Parity, FWIW. Hopefully I'm doing something wrong, I was excited that this was finally closed!

**Comment by davidmurdoch** [comment]
This is probably just a typo in your comment, but make sure you are using ganache-cli@6.4.3, which i'm pretty sure you are (ganache-core _is_ at 2.5.5, which is what ships in cli@6.4.3).

Can you provide the original transaction or hash?

Can you check if the `txHash` passed to the exported function here is a `Buffer`?

**Comment by gnidan** [comment]
I tried passing it as a string and as a BN, does it need to be a buffer?

**Comment by gnidan** [comment]
I just picked an arbitrary recent contract transaction for testing this out... I'm using 0xca2290078bdc838584cbeca83a8b424ae1872a9af43e14eb09d6249cf73f107f on Görli.

So I tried converting `txHash` to a Buffer and a Uint8Array, and if I do that, Ganache doesn't crash anymore, but I still don't get a result. Instead, I get this RPC error:
```javascript
{ id: 1556481539476,
  jsonrpc: '2.0',
  error:
   { message: 'Returned error: invalid argument 0: json: cannot unmarshal hex string of odd length into Go value of type common.Hash',
     code: -32000,
     data:
      { stack: 'Error: Returned error: invalid argument 0: json: cannot unmarshal hex string of odd length into Go value of type common.Hash\n    at Object.ErrorResponse (/Users/gnidan/.nvm/versions/node/v8.15.0/lib/node_modules/ganache-cli/build/ganache-core.node.cli.js:69:19965)\n    at /Users/gnidan/.nvm/versions/node/v8.15.0/lib/node_modules/ganache-cli/build/ganache-core.node.cli.js:69:18842\n    at t.a.onreadystatechange (/Users/gnidan/.nvm/versions/node/v8.15.0/lib/node_modules/ganache-cli/build/ganache-core.node.cli.js:97:10715)\n    at t.e.dispatchEvent (/Users/gnidan/.nvm/versions/node/v8.15.0/lib/node_modules/ganache-cli/build/ganache-core.node.cli.js:47:33383)\n    at t._setReadyState (/Users/gnidan/.nvm/versions/node/v8.15.0/lib/node_modules/ganache-cli/build/ganache-core.node.cli.js:97:15658)\n    at t._onHttpResponseEnd (/Users/gnidan/.nvm/versions/node/v8.15.0/lib/node_modules/ganache-cli/build/ganache-core.node.cli.js:97:18743)\n    at IncomingMessage.<anonymous> (/Users/gnidan/.nvm/versions/node/v8.15.0/lib/node_modules/ganache-cli/build/ganache-core.node.cli.js:97:18001)\n    at emitNone (events.js:111:20)\n    at IncomingMessage.emit (events.js:208:7)\n    at endReadableNT (_stream_readable.js:1064:12)\n    at _combinedTickCallback (internal/process/next_tick.js:139:11)\n    at process._tickCallback (internal/process/next_tick.js:181:9)',
        name: 'Error' } } }
```

This is forking geth; same issue whether or not the debug rpcapi is enabled.
